name: flutter_firebase_login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

        
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.1

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  google_sign_in: ^4.0.7
  font_awesome_flutter: ^8.5.0
  fl_chart: ^0.2.2
  curved_navigation_bar: ^0.3.1 
  shared_preferences: ^0.5.3+4
  flutter_bloc: ^0.21.0
  bubble: ^1.1.9+1
  equatable: ^0.2.0
  meta: ^1.1.6
  auto_size_text : ^2.1.0
  fancy_bottom_navigation: ^0.3.2
  liquid_pull_to_refresh: ^1.1.1
  sliver_glue: ^1.2.0
  sticky_headers: ^0.1.8
  flutter_custom_clippers: ^1.0.4
  easy_listview: ^0.1.3
  flushbar: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Opensans
    fonts:
      - asset : assets/fonts/OpenSans-Regular.ttf
  - family: Monsterrat
    fonts:
      - asset : assets/fonts/Montserrat-Regular.ttf
  - family: MonsterratBold
    fonts:
      - asset : assets/fonts/Montserrat-Bold.ttf
        
